// ─── REVIEWED REFERENCE ──────────────────────────────────────────────────────
// The things SparkConnect will state as fact, and the citation behind each one.
//
// This is what sits between "computed by an engine" and "generated by a model".
// An entry here is a claim the app makes in its own voice, so two rules hold:
//
//   1. Every citation must resolve against src/nec/citations.js. A test walks
//      the whole table and fails on any that does not, which means an entry
//      cannot be added with a reference nobody checked.
//   2. Entries state PRINCIPLE, never a specific installation's answer. "The
//      yoke counts twice" belongs here. "Use a 4-11/16 box" does not — that is
//      a calculation, and calculations come from tools.js.
//
// Pure module: no React, no network, no storage.

const entry = (def) => Object.freeze({
  ...def,
  tags: Object.freeze(def.tags),
  refs: Object.freeze(def.refs),
});

export const KNOWLEDGE = Object.freeze([
  entry({
    id: 'box-fill', topic: 'Box fill', tab: 'boxfill',
    tags: ['box fill', 'box size', 'cubic inches', '314.16', 'how big a box'],
    short: 'Count every conductor entering the box, count each device yoke twice, count all grounds as one, and count all internal clamps as one.',
    explain: 'Volume allowance is per conductor size. A conductor that enters and leaves counts once; a pigtail that begins and ends inside the box does not count at all. The commonest overshoot is counting each ground separately — all equipment grounding conductors together are a single allowance, based on the largest one present.',
    refs: ['NEC 314.16(B)'],
  }),
  entry({
    id: 'conduit-fill', topic: 'Conduit fill', tab: 'conduitfill',
    tags: ['conduit fill', 'raceway fill', '40 percent', 'chapter 9', 'how many wires'],
    short: 'One conductor may fill 53%, two may fill 31%, and three or more may fill 40% — all of them percentages of the conduit’s TOTAL internal area.',
    explain: 'Table 4 gives the total internal area of each conduit and trade size; Table 5 gives the area of each conductor including insulation. The percentage is taken against the total, not against the 40% column printed beside it — using that column as the denominator is a common error that rejects installations the code permits.',
    refs: ['NEC Chapter 9, Table 1'],
  }),
  entry({
    id: 'voltage-drop', topic: 'Voltage drop', tab: 'volt',
    tags: ['voltage drop', 'vd', '3 percent', 'long run'],
    short: 'The 3% branch-circuit and 5% total figures are recommendations in informational notes, not mandatory rules — though an AHJ may enforce them.',
    explain: 'Drop depends on conductor resistance, current, and the length of the whole path. A single-phase circuit counts the run twice because the current goes out and comes back; a three-phase circuit uses the square root of three instead. Upsizing the conductor is the usual fix.',
    refs: ['NEC 210.19(A)'],
  }),
  entry({
    id: 'egc-purpose', topic: 'Equipment grounding', tab: null,
    tags: ['egc', 'equipment ground', 'ground wire', 'fault path', 'why ground'],
    short: 'The equipment grounding conductor exists to give fault current a low-impedance path back to the source so the overcurrent device opens quickly.',
    explain: 'It is not there to carry load current and it is not a substitute for the grounded conductor. Its whole job is to make a fault look like a short to the breaker, so the breaker clears it before the metal someone is touching stays energized.',
    refs: ['NEC 250.4(A)(5)'],
  }),
  entry({
    id: 'switched-neutral', topic: 'Never switch the grounded conductor', tab: 'wiringlab',
    tags: ['switched neutral', 'switch the neutral', 'grounded conductor', '404.2'],
    short: 'A switch may interrupt the ungrounded conductor only. Putting the switch in the grounded conductor leaves the load energized when the switch reads off.',
    explain: 'This is the fault that looks like it works: the lamp goes on and off, the customer is satisfied, and the fixture stays live. Someone opening it expects it to be dead. SparkConnect’s circuit engine reports this as its own named failure rather than as a generic continuity problem, because it is the one a learner most needs to recognise.',
    refs: ['NEC 404.2(B)'],
  }),
  entry({
    id: 'gfci-line-load', topic: 'GFCI line and load', tab: null,
    tags: ['gfci', 'line and load', 'line load', 'reversed gfci'],
    short: 'A GFCI’s line and load terminals are not interchangeable. Reversed, the device still appears to work while everything downstream is unprotected.',
    explain: 'Line is the supply. Load feeds the receptacles downstream that the GFCI is meant to protect. Wire them backwards and the GFCI itself tests fine at the face, which is exactly why the mistake survives. Note the contrast with a plain mechanical single-pole switch, whose two brass screws genuinely are interchangeable — that is specific to that device and does not generalise to dimmers, timers, smart switches, or occupancy sensors, all of which are marked LINE and LOAD.',
    refs: ['NEC 210.8'],
  }),
  entry({
    id: 'continuous-load', topic: 'Continuous loads', tab: 'volt',
    tags: ['continuous load', '125 percent', '3 hours', 'breaker sizing'],
    short: 'Where a load runs for three hours or more, the overcurrent device and the conductors are sized at 125% of that load.',
    explain: 'The 125% is not a safety margin invented for comfort — it accounts for the heating that sustained current produces in the terminations and the conductor. Lighting in a commercial space is the usual example.',
    refs: ['NEC 210.20(A)'],
  }),
  entry({
    id: 'working-space', topic: 'Working space', tab: null,
    tags: ['working space', 'clearance', '110.26', 'in front of the panel'],
    short: 'Equipment likely to be worked on energized needs a clear working space: depth by voltage and condition, at least 30 inches wide or the width of the equipment, and clear to 6½ feet high.',
    explain: 'Depth is set by a table that depends on the voltage to ground and what is on the opposite side of the space. The width and height requirements are the ones most often lost to a stack of material during construction.',
    refs: ['NEC 110.26(A)(1)'],
  }),
  entry({
    id: 'small-conductor', topic: 'The small-conductor rule', tab: 'ampacity',
    tags: ['small conductor', '240.4', '12 awg 20 amp', 'overcurrent limit'],
    short: 'Regardless of what the ampacity table allows after correction, overcurrent protection for small copper conductors is capped: 15 A for 14 AWG, 20 A for 12 AWG, 30 A for 10 AWG.',
    explain: 'This is why a 12 AWG THHN conductor rated 30 A at 90°C still ends up on a 20 A breaker. Derating and temperature correction happen first; this cap then has the last word if it is more restrictive.',
    refs: ['NEC 240.4(D)'],
  }),
  entry({
    id: 'ampacity-adjustment', topic: 'Adjustment for conductor count', tab: 'ampacity',
    tags: ['derate', 'derating', 'adjustment factor', 'current carrying conductors'],
    short: 'More than three current-carrying conductors in a raceway reduces their allowable ampacity: 80% for four to six, 70% for seven to nine, 50% for ten to twenty.',
    explain: 'A conductor carrying only the unbalanced current of a multiwire branch circuit is not counted as current-carrying. Adjustment is applied to the ampacity from the conductor’s own temperature column, and the result is then subject to the termination rating and the small-conductor rule.',
    refs: ['NEC 310.15(C)(1)'],
  }),
]);

const norm = (s) => String(s ?? '').toLowerCase();

/**
 * Find the entry a question is about, or null.
 *
 * Longest tag wins, so "conduit fill" beats "fill". Returns null freely —
 * a miss routes the question onward, and a wrong hit would answer confidently
 * about the wrong topic.
 */
export const find = (question) => {
  const q = norm(question);
  if (!q.trim()) return null;

  let best = null;
  let bestLen = 0;
  for (const e of KNOWLEDGE) {
    for (const tag of e.tags) {
      if (q.includes(norm(tag)) && tag.length > bestLen) { best = e; bestLen = tag.length; }
    }
  }
  return best;
};

export const byId = (id) => KNOWLEDGE.find((e) => e.id === id) ?? null;
export const topics = () => KNOWLEDGE.map((e) => Object.freeze({ id: e.id, topic: e.topic, tab: e.tab }));

/** The interface sparkai.ask expects. */
export const knowledgeBase = Object.freeze({ find, byId, topics, all: KNOWLEDGE });
