import { useState, useEffect, useCallback } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Sparky AI limits — 20/day Pro with 400/month fair-use cap
export const SPARKY_LIMITS = { FREE: 3, PRO_DAILY: 20, PRO_MONTHLY: 400 };
export const CALC_LIMITS = { BOX_FILL: 3, CONDUIT: 3 };

const K = {
  BF_USES: '@sc_boxfill_uses', BF_DATE: '@sc_boxfill_date',
    CO_USES: '@sc_conduit_uses', CO_DATE: '@sc_conduit_date',
      SP_USES: '@sc_sparky_uses', SP_DATE: '@sc_sparky_date',
        SP_MONTH_USES: '@sc_sparky_month_uses', SP_MONTH: '@sc_sparky_month',
          REF_CODE: '@sc_referral_code', REF_EXPIRY: '@sc_referral_expiry',
          };

          function todayStr() { return new Date().toISOString().split('T')[0]; }
          function monthStr() { const d = new Date(); return d.getFullYear()+'-'+(d.getMonth()+1); }

          async function getOrReset(usesKey, dateKey, limit) {
            const [u, d] = await Promise.all([AsyncStorage.getItem(usesKey), AsyncStorage.getItem(dateKey)]);
              const today = todayStr();
                if (d !== today) {
                    await Promise.all([AsyncStorage.setItem(usesKey,'0'), AsyncStorage.setItem(dateKey, today)]);
                        return { uses: 0, remaining: limit };
                          }
                            const uses = parseInt(u ?? '0', 10);
                              return { uses, remaining: Math.max(0, limit - uses) };
                              }

                              export function useBoxFillGate(isPro) {
                                const [uses, setUses] = useState(0);
                                  const [remaining, setRemaining] = useState(CALC_LIMITS.BOX_FILL);
                                    const [loaded, setLoaded] = useState(false);
                                      useEffect(() => {
                                          if (isPro) { setLoaded(true); return; }
                                              getOrReset(K.BF_USES, K.BF_DATE, CALC_LIMITS.BOX_FILL)
                                                    .then(({ uses: u, remaining: r }) => { setUses(u); setRemaining(r); setLoaded(true); });
                                                      }, [isPro]);
                                                        const recordUse = useCallback(async () => {
                                                            if (isPro) return { allowed: true };
                                                                const next = uses + 1; const rem = Math.max(0, CALC_LIMITS.BOX_FILL - next);
                                                                    await AsyncStorage.setItem(K.BF_USES, String(next));
                                                                        setUses(next); setRemaining(rem);
                                                                            return { allowed: next <= CALC_LIMITS.BOX_FILL, remaining: rem };
                                                                              }, [isPro, uses]);
                                                                                const checkAllowed = useCallback(() => isPro || remaining > 0, [isPro, remaining]);
                                                                                  return { loaded, uses, remaining, limit: CALC_LIMITS.BOX_FILL, checkAllowed, recordUse,
                                                                                      label: isPro ? null : `${remaining} of ${CALC_LIMITS.BOX_FILL} free calculations today` };
                                                                                      }

                                                                                      export function useConduitGate(isPro) {
                                                                                        const [uses, setUses] = useState(0);
                                                                                          const [remaining, setRemaining] = useState(CALC_LIMITS.CONDUIT);
                                                                                            const [loaded, setLoaded] = useState(false);
                                                                                              useEffect(() => {
                                                                                                  if (isPro) { setLoaded(true); return; }
                                                                                                      getOrReset(K.CO_USES, K.CO_DATE, CALC_LIMITS.CONDUIT)
                                                                                                            .then(({ uses: u, remaining: r }) => { setUses(u); setRemaining(r); setLoaded(true); });
                                                                                                              }, [isPro]);
                                                                                                                const recordUse = useCallback(async () => {
                                                                                                                    if (isPro) return { allowed: true };
                                                                                                                        const next = uses + 1; const rem = Math.max(0, CALC_LIMITS.CONDUIT - next);
                                                                                                                            await AsyncStorage.setItem(K.CO_USES, String(next));
                                                                                                                                setUses(next); setRemaining(rem);
                                                                                                                                    return { allowed: next <= CALC_LIMITS.CONDUIT, remaining: rem };
                                                                                                                                      }, [isPro, uses]);
                                                                                                                                        const checkAllowed = useCallback(() => isPro || remaining > 0, [isPro, remaining]);
                                                                                                                                          return { loaded, uses, remaining, limit: CALC_LIMITS.CONDUIT, checkAllowed, recordUse,
                                                                                                                                              label: isPro ? null : `${remaining} of ${CALC_LIMITS.CONDUIT} free calculations today` };
                                                                                                                                              }

                                                                                                                                              export function useSparkyGate(isPro) {
                                                                                                                                                  const dailyLimit = isPro ? SPARKY_LIMITS.PRO_DAILY : SPARKY_LIMITS.FREE;
                                                                                                                                                    const [dailyUses, setDailyUses] = useState(0);
                                                                                                                                                      const [dailyRemaining, setDailyRemaining] = useState(dailyLimit);
                                                                                                                                                        const [monthUses, setMonthUses] = useState(0);
                                                                                                                                                          const [loaded, setLoaded] = useState(false);

                                                                                                                                                            useEffect(() => {
                                                                                                                                                                (async () => {
                                                                                                                                                                      const [daily, monthly] = await Promise.all([
                                                                                                                                                                              getOrReset(K.SP_USES, K.SP_DATE, dailyLimit),
                                                                                                                                                                                      (async () => {
                                                                                                                                                                                                const [u, m] = await Promise.all([AsyncStorage.getItem(K.SP_MONTH_USES), AsyncStorage.getItem(K.SP_MONTH)]);
                                                                                                                                                                                                          const cur = monthStr();
                                                                                                                                                                                                                    if (m !== cur) { await Promise.all([AsyncStorage.setItem(K.SP_MONTH_USES,'0'), AsyncStorage.setItem(K.SP_MONTH, cur)]); return 0; }
                                                                                                                                                                                                                              return parseInt(u ?? '0', 10);
                                                                                                                                                                                                                                      })(),
                                                                                                                                                                                                                                            ]);
                                                                                                                                                                                                                                                  setDailyUses(daily.uses); setDailyRemaining(daily.remaining);
                                                                                                                                                                                                                                                        setMonthUses(monthly); setLoaded(true);
                                                                                                                                                                                                                                                            })();
                                                                                                                                                                                                                                                              }, [isPro]);

                                                                                                                                                                                                                                                                const checkAllowed = useCallback(() => {
                                                                                                                                                                                                                                                                    if (dailyRemaining <= 0) return false;
                                                                                                                                                                                                                                                                        if (isPro && monthUses >= SPARKY_LIMITS.PRO_MONTHLY) return false;
                                                                                                                                                                                                                                                                            return true;
                                                                                                                                                                                                                                                                              }, [dailyRemaining, monthUses, isPro]);

                                                                                                                                                                                                                                                                                const recordUse = useCallback(async () => {
                                                                                                                                                                                                                                                                                    const nextDaily = dailyUses + 1;
                                                                                                                                                                                                                                                                                        const nextMonth = monthUses + 1;
                                                                                                                                                                                                                                                                                            const remDaily = Math.max(0, dailyLimit - nextDaily);
                                                                                                                                                                                                                                                                                                await Promise.all([
                                                                                                                                                                                                                                                                                                      AsyncStorage.setItem(K.SP_USES, String(nextDaily)),
                                                                                                                                                                                                                                                                                                            AsyncStorage.setItem(K.SP_MONTH_USES, String(nextMonth)),
                                                                                                                                                                                                                                                                                                                ]);
                                                                                                                                                                                                                                                                                                                    setDailyUses(nextDaily); setDailyRemaining(remDaily); setMonthUses(nextMonth);
                                                                                                                                                                                                                                                                                                                        return { allowed: nextDaily <= dailyLimit && (!isPro || nextMonth <= SPARKY_LIMITS.PRO_MONTHLY), remaining: remDaily };
                                                                                                                                                                                                                                                                                                                          }, [dailyUses, monthUses, dailyLimit, isPro]);

                                                                                                                                                                                                                                                                                                                            const hitMonthCap = isPro && monthUses >= SPARKY_LIMITS.PRO_MONTHLY;
                                                                                                                                                                                                                                                                                                                              const label = hitMonthCap
                                                                                                                                                                                                                                                                                                                                  ? 'Monthly fair-use limit reached — add an answer pack'
                                                                                                                                                                                                                                                                                                                                      : `${dailyRemaining} of ${dailyLimit} ${isPro ? 'Pro' : 'free'} answers remaining today`;

                                                                                                                                                                                                                                                                                                                                        return { loaded, dailyUses, dailyRemaining, monthUses, dailyLimit, checkAllowed, recordUse, label, hitMonthCap };
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        export function useReferral() {
                                                                                                                                                                                                                                                                                                                                          const [code, setCode] = useState(null);
                                                                                                                                                                                                                                                                                                                                            useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                (async () => {
                                                                                                                                                                                                                                                                                                                                                      let stored = await AsyncStorage.getItem(K.REF_CODE);
                                                                                                                                                                                                                                                                                                                                                            if (!stored) {
                                                                                                                                                                                                                                                                                                                                                                    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
                                                                                                                                                                                                                                                                                                                                                                            let r = ''; for (let i = 0; i < 4; i++) r += chars[Math.floor(Math.random() * chars.length)];
                                                                                                                                                                                                                                                                                                                                                                                    stored = `SPARK-${r}`;
                                                                                                                                                                                                                                                                                                                                                                                            await AsyncStorage.setItem(K.REF_CODE, stored);
                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                        setCode(stored);
                                                                                                                                                                                                                                                                                                                                                                                                            })();
                                                                                                                                                                                                                                                                                                                                                                                                              }, []);
                                                                                                                                                                                                                                                                                                                                                                                                                const redeemCode = useCallback(async (inputCode) => {
                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                          const res = await fetch('https://sparkconnect-website.vercel.app/api/referral', {
                                                                                                                                                                                                                                                                                                                                                                                                                                  method: 'POST', headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                          body: JSON.stringify({ code: inputCode.toUpperCase().trim() }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const data = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (data.valid) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const exp = new Date(); exp.setDate(exp.getDate() + 7);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await AsyncStorage.setItem(K.REF_EXPIRY, exp.toISOString());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return { success: true };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { success: false, error: data.error || 'Invalid code' };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch(e) { return { success: false, error: 'Network error' }; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }, []);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return { code, redeemCode };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                              }