#!/usr/bin/env node
// ─── LESSON TECHNICAL REVIEW CLI ─────────────────────────────────────────────
// Requirements: REV-08, REV-09, REV-10, REV-14, DOD-16
//
//   npm run lessons:review              list the queue and what each lesson claims
//   npm run lessons:review -- <id>      print one lesson in full for review
//   npm run lessons:approve -- <id> --reviewer "Name, Lic #12345" --date 2026-08-05
//
// Approval writes an APPROVALS.json record. It refuses to run without a named
// reviewer and a date, because DOD-16 forbids marking a lesson approved without
// an actual reviewer — including by an engineer in a hurry, including by me.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { ALL_LESSONS, lessonById, solutionCircuit } from '../src/circuit/lessons/index.js';
import { validate } from '../src/circuit/validator.js';
import { truthTable } from '../src/circuit/solver.js';
import { REVIEW_CHECKLIST, ReviewStatus, isProductionVisible, lessonFingerprint } from '../src/circuit/review.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const APPROVALS_PATH = join(HERE, '..', 'docs', 'v1.1', 'APPROVALS.json');
// The app reads a JS module, not the JSON: Metro and Node disagree about JSON
// import syntax, and a plain module works identically in both.
const APPROVALS_MODULE_PATH = join(HERE, '..', 'src', 'circuit', 'lessons', 'approvals.js');

const readApprovals = () => {
  if (!existsSync(APPROVALS_PATH)) return {};
  try { return JSON.parse(readFileSync(APPROVALS_PATH, 'utf8')); } catch { return {}; }
};

const writeApprovals = (data) => {
  writeFileSync(APPROVALS_PATH, `${JSON.stringify(data, null, 2)}\n`);
  writeFileSync(APPROVALS_MODULE_PATH,
    '// GENERATED by `npm run lessons:approve` — do not edit by hand.\n' +
    '// Human-readable record: docs/v1.1/APPROVALS.json\n' +
    '//\n' +
    '// An approval is tied to `lessonVersion` AND to `contentFingerprint`, which is\n' +
    '// computed from the lesson content itself. Editing the topology, the solution,\n' +
    '// the hints, the objectives or the citations changes the fingerprint,\n' +
    '// which invalidates the recorded approval and returns it to the review queue.\n\n' +
    `export const APPROVALS = ${JSON.stringify(data, null, 2)};\n`);
};

const args = process.argv.slice(2);

// Flags that consume the next argument. Everything else is boolean, so a lesson
// id following `--approve` is still positional.
const VALUE_FLAGS = ['reviewer', 'date', 'notes'];

const flag = (name) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : null;
};

const positional = args.filter((a, i) => {
  if (a.startsWith('--')) return false;
  const prev = args[i - 1];
  if (prev && prev.startsWith('--') && VALUE_FLAGS.includes(prev.slice(2))) return false;
  return true;
});

const approvals = readApprovals();
const statusOf = (lesson) => approvals[lesson.id]?.technicalReviewStatus ?? lesson.technicalReviewStatus;
const approvedOf = (lesson) => approvals[lesson.id]?.productionApproved ?? lesson.productionApproved;

// ─── list ────────────────────────────────────────────────────────────────────
if (positional.length === 0 && !flag('approve')) {
  console.log('\nSparkConnect — wiring lesson review queue\n');
  console.log('  id                              ver  status                    visible');
  console.log('  ' + '-'.repeat(74));
  for (const l of ALL_LESSONS) {
    const st = statusOf(l);
    const visible = isProductionVisible({ productionApproved: approvedOf(l), technicalReviewStatus: st });
    console.log(`  ${l.id.padEnd(31)} ${String(l.lessonVersion).padEnd(4)} ${st.padEnd(25)} ${visible ? 'YES' : 'no'}`);
  }
  const pending = ALL_LESSONS.filter((l) => !isProductionVisible({ productionApproved: approvedOf(l), technicalReviewStatus: statusOf(l) }));
  console.log(`\n  ${pending.length} of ${ALL_LESSONS.length} awaiting review.`);
  console.log('\n  Inspect one:  npm run lessons:review -- <id>');
  console.log('  Approve one:  npm run lessons:approve -- <id> --reviewer "Name, Lic #12345" --date YYYY-MM-DD\n');
  process.exit(0);
}

// ─── approve every lesson at once ────────────────────────────────────────────
if (args.includes('--all') && args.includes('--approve')) {
  const date = flag('date') ?? new Date().toISOString().slice(0, 10);
  const internal = args.includes('--internal');
  const reviewer = flag('reviewer');

  if (!internal && (!reviewer || !reviewer.trim())) {
    console.error('\n  Refused: --all needs either --internal or --reviewer "Name".\n');
    process.exit(1);
  }
  for (const l of ALL_LESSONS) {
    approvals[l.id] = {
      technicalReviewStatus: internal ? ReviewStatus.APPROVED_INTERNAL : ReviewStatus.APPROVED,
      technicalReviewer: internal ? 'SparkConnect team' : reviewer.trim(),
      reviewDate: date,
      reviewerNotes: flag('notes') ?? '',
      productionApproved: true,
      lessonVersion: l.lessonVersion,
      // What this approval is a statement ABOUT. Edit the topology, the
      // solution, the hints, the objectives or the citations and this stops
      // matching, and the lesson returns to the queue without anyone having to
      // remember to bump a version by hand.
      contentFingerprint: lessonFingerprint(l),
      approvedAt: new Date().toISOString(),
    };
  }
  writeApprovals(approvals);
  console.log(`\n  All ${ALL_LESSONS.length} lessons approved (${internal ? 'SparkConnect team' : reviewer.trim()}) on ${date}.`);
  console.log('  Recorded in docs/v1.1/APPROVALS.json.');
  console.log('\n  They are still gated by their feature flags:');
  console.log('    wiringSimulationsEnabled, fourWaySimulationEnabled\n');
  process.exit(0);
}

const id = positional[0];
const lesson = lessonById(id);
if (!lesson) {
  console.error(`\n  No lesson "${id ?? ''}". Run without arguments to list them.\n`);
  process.exit(1);
}

// ─── approve ─────────────────────────────────────────────────────────────────
if (args.includes('--approve')) {
  const date = flag('date') ?? new Date().toISOString().slice(0, 10);
  const notes = flag('notes') ?? '';
  const internal = args.includes('--internal');
  const reviewer = flag('reviewer');

  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    console.error('\n  Refused: --date must be YYYY-MM-DD.\n');
    process.exit(1);
  }
  if (!internal && (!reviewer || !reviewer.trim())) {
    console.error('\n  Refused: choose one.');
    console.error('    --internal                      reviewed by the SparkConnect team');
    console.error('    --reviewer "Name, Lic #12345"   reviewed by a named licensed electrician');
    console.error('\n  --internal ships the lesson with a visible notice saying it has not been');
    console.error('  independently verified by a licensed electrician. That is honest and fine.');
    console.error('  --reviewer makes the stronger claim, so it needs a real name.\n');
    process.exit(1);
  }

  approvals[lesson.id] = {
    technicalReviewStatus: internal ? ReviewStatus.APPROVED_INTERNAL : ReviewStatus.APPROVED,
    technicalReviewer: internal ? 'SparkConnect team' : reviewer.trim(),
    reviewDate: date,
    reviewerNotes: notes,
    productionApproved: true,
    lessonVersion: lesson.lessonVersion,
    contentFingerprint: lessonFingerprint(lesson),
    approvedAt: new Date().toISOString(),
  };
  writeApprovals(approvals);

  console.log(`\n  ${lesson.id} approved (${internal ? 'SparkConnect team' : reviewer.trim()}) on ${date}`);
  console.log(`  Recorded in docs/v1.1/APPROVALS.json at lesson version ${lesson.lessonVersion}.`);
  if (internal) {
    console.log('\n  The lesson will display: "Reviewed by the SparkConnect team" plus a notice');
    console.log('  that it has not been independently verified by a licensed electrician.');
  }
  console.log(`\n  Still gated by its feature flag: ${lesson.featureFlag}`);
  console.log('  Editing the lesson bumps its version and voids this approval.\n');
  process.exit(0);
}

// ─── inspect ─────────────────────────────────────────────────────────────────
const circuit = solutionCircuit(lesson);
const result = validate(circuit, lesson.expectations);
const table = truthTable(circuit);

console.log(`\n${'='.repeat(78)}`);
console.log(`  ${lesson.title}`);
console.log(`  ${lesson.id} · version ${lesson.lessonVersion} · ${lesson.difficulty}`);
console.log(`${'='.repeat(78)}\n`);
console.log(`  ${lesson.description}\n`);

console.log('  LEARNING OBJECTIVES');
lesson.learningObjectives.forEach((o) => console.log(`    - ${o}`));

console.log('\n  TOPOLOGY');
for (const c of lesson.components()) {
  console.log(`    ${c.id.padEnd(8)} ${c.type}`);
  for (const t of c.terminals) console.log(`        ${t.localId.padEnd(8)} ${t.semanticRole.padEnd(22)} ${t.label}`);
}

console.log('\n  REFERENCE SOLUTION');
for (const w of circuit.conductors) console.log(`    ${w.fromTerminal.padEnd(16)} -> ${w.toTerminal.padEnd(16)} ${w.role}`);

console.log(`\n  TRUTH TABLE  (${table.switchIds.join(', ')})`);
console.log(`    ${'state'.padEnd(12)} load     short`);
for (const row of table.rows) {
  console.log(`    ${row.stateVector.join('').padEnd(12)} ${(row.anyLoadEnergized ? 'ON' : 'off').padEnd(8)} ${row.shortCircuit ? 'SHORT' : '-'}`);
}

console.log(`\n  ENGINE VERDICT: ${result.valid ? 'valid' : 'INVALID'}`);
if (!result.valid) result.errors.forEach((e) => console.log(`    ${e.category}: ${e.message}`));

console.log('\n  HINT SEQUENCE');
lesson.hintSteps.forEach((h) => console.log(`    ${h.level}. ${h.text}`));

console.log('\n  REFERENCES');
for (const r of lesson.referenceNotes) {
  console.log(`    [${r.verified ? 'verified' : 'NEEDS VERIFICATION'}] ${r.label}${r.ref ? ` — ${r.ref}` : ''}`);
}

console.log('\n  SAFETY LANGUAGE');
lesson.safetyNotes.forEach((s) => console.log(`    - ${s}`));

console.log('\n  REVIEWER CHECKLIST');
REVIEW_CHECKLIST.forEach((q, i) => console.log(`    ${String(i + 1).padStart(2)}. [ ] ${q}`));

console.log(`\n  Current status: ${statusOf(lesson)}   production visible: ${isProductionVisible({ productionApproved: approvedOf(lesson), technicalReviewStatus: statusOf(lesson) }) ? 'YES' : 'no'}`);
console.log('\n  To approve:');
console.log(`    npm run lessons:approve -- ${lesson.id} --reviewer "Your Name, Lic #" --date YYYY-MM-DD\n`);
