// ─── DAILY CODE QUESTION BANK ────────────────────────────────────────────────
// Single source of truth for the "Daily Code Question" shown on Home AND sent
// as the 7:30 AM notification. Both must agree for a given calendar date, so
// selection is a pure function of the local date — never of "now".
//
// NOTE: answers reference the 2023 NEC unless the question says otherwise.

export const NEC_QUESTIONS = [
  {id:'q1',question:'Max recommended voltage drop for a branch circuit per NEC informational notes?',choices:['2%','3%','5%','10%'],correct:1,explanation:'NEC 210.19(A) Informational Note recommends ≤3% on branch circuits, ≤5% total feeder + branch.',ref:'NEC 210.19(A)',difficulty:'Apprentice',category:'Voltage Drop'},
  {id:'q2',question:'GFCI protection is required for 125V 15/20A receptacles in which location?',choices:['Living rooms','Bathrooms','Closets','Hallways'],correct:1,explanation:'NEC 210.8(A)(1) requires GFCI in all dwelling bathrooms, plus kitchens, garages, outdoors, and more.',ref:'NEC 210.8(A)(1)',difficulty:'Apprentice',category:'GFCI'},
  {id:'q3',question:'A continuous load OCPD must be rated at what % of the load?',choices:['100%','115%','125%','150%'],correct:2,explanation:'NEC 210.20(A): OCPD ≥125% of continuous load. Continuous = 3+ hours of operation.',ref:'NEC 210.20(A)',difficulty:'Journeyman',category:'Overcurrent'},
  {id:'q4',question:'A #12 AWG conductor counts as how many cubic inches in box fill?',choices:['1.75','2.00','2.25','2.50'],correct:2,explanation:'NEC 314.16(B) Table: #12 AWG = 2.25 in³ per conductor.',ref:'NEC 314.16(B)',difficulty:'Apprentice',category:'Box Fill'},
  {id:'q5',question:'Max conduit fill % for 3 or more conductors?',choices:['31%','40%','53%','60%'],correct:1,explanation:'NEC Ch.9 Table 1: 53% (1 wire), 31% (2 wires), 40% (3+ wires).',ref:'NEC Chapter 9, Table 1',difficulty:'Journeyman',category:'Conduit Fill'},
  {id:'q6',question:'The EGC primarily provides what?',choices:['Load current return','Low-impedance fault path to trip OCPD','Voltage drop reduction','120V neutral'],correct:1,explanation:'NEC 250.4(A)(5): the EGC provides a low-impedance fault-current path so the breaker trips fast.',ref:'NEC 250.4(A)(5)',difficulty:'Apprentice',category:'Grounding'},
  {id:'q7',question:'Which NEC article covers EV charging equipment?',choices:['Article 210','Article 250','Article 625','Article 700'],correct:2,explanation:'NEC Article 625 covers EVSE: circuit sizing, GFCI, and disconnecting means.',ref:'NEC Article 625',difficulty:'Journeyman',category:'EV Charging'},
  {id:'q8',question:'Max equivalent 90° bends in EMT between pull points?',choices:['180°','270°','360°','450°'],correct:2,explanation:'NEC 358.26 limits total bends to 360° (four quarter-bends) between pull boxes.',ref:'NEC 358.26',difficulty:'Apprentice',category:'Conduit'},

  {id:'q9',question:'Along a dwelling wall, no point may be farther than what distance from a receptacle?',choices:['4 ft','6 ft','8 ft','12 ft'],correct:1,explanation:'NEC 210.52(A)(1): no point along the floor line may be more than 6 ft from a receptacle — which works out to receptacles spaced no more than 12 ft apart.',ref:'NEC 210.52(A)(1)',difficulty:'Apprentice',category:'Receptacles'},
  {id:'q10',question:'Per the small-conductor rule, the max OCPD for #12 AWG copper is:',choices:['15A','20A','25A','30A'],correct:1,explanation:'NEC 240.4(D)(5): #14 Cu = 15A, #12 Cu = 20A, #10 Cu = 30A, regardless of the ampacity table.',ref:'NEC 240.4(D)',difficulty:'Apprentice',category:'Overcurrent'},
  {id:'q11',question:'Minimum number of 20A small-appliance branch circuits for a dwelling kitchen:',choices:['1','2','3','4'],correct:1,explanation:'NEC 210.11(C)(1) requires at least two 20A small-appliance branch circuits serving the kitchen, pantry, breakfast room and dining room receptacles.',ref:'NEC 210.11(C)(1)',difficulty:'Apprentice',category:'Branch Circuits'},
  {id:'q12',question:'General lighting load for a dwelling unit is calculated at:',choices:['1 VA/ft²','2 VA/ft²','3 VA/ft²','5 VA/ft²'],correct:2,explanation:'NEC Table 220.12: dwelling units are calculated at 3 VA per ft² of floor area, using outside dimensions.',ref:'NEC 220.12',difficulty:'Journeyman',category:'Load Calc'},
  {id:'q13',question:'With 4 to 6 current-carrying conductors in a raceway, the ampacity adjustment factor is:',choices:['70%','80%','50%','35%'],correct:1,explanation:'NEC Table 310.15(C)(1): 4–6 CCC = 80%, 7–9 = 70%, 10–20 = 50%. The neutral of a balanced 3-wire circuit is not counted.',ref:'NEC 310.15(C)(1)',difficulty:'Journeyman',category:'Ampacity'},
  {id:'q14',question:'Minimum length of a rod-type grounding electrode:',choices:['6 ft','8 ft','10 ft','12 ft'],correct:1,explanation:'NEC 250.52(A)(5): rod electrodes must be at least 8 ft long and driven full length in contact with soil.',ref:'NEC 250.52(A)(5)',difficulty:'Apprentice',category:'Grounding'},
  {id:'q15',question:'A single ground rod needs no supplemental electrode if its resistance to earth is:',choices:['≤5 ohms','≤10 ohms','≤25 ohms','≤50 ohms'],correct:2,explanation:'NEC 250.53(A)(2) Exception: a single rod, pipe or plate electrode with ≤25 ohms to earth needs no supplemental electrode. Otherwise add a second, 6 ft away.',ref:'NEC 250.53(A)(2)',difficulty:'Journeyman',category:'Grounding'},
  {id:'q16',question:'Minimum EGC size for a 20A branch circuit (copper):',choices:['#14','#12','#10','#8'],correct:0,explanation:'NEC Table 250.122: 15A and 20A circuits = #14 Cu EGC; 30–60A = #10 Cu; 100A = #8 Cu.',ref:'NEC 250.122',difficulty:'Apprentice',category:'Grounding'},
  {id:'q17',question:'Minimum working space depth in front of 120/240V equipment, Condition 1:',choices:['2 ft','3 ft','3.5 ft','4 ft'],correct:1,explanation:'NEC Table 110.26(A)(1): 0–150V to ground, Condition 1 = 3 ft. Width is 30 in or the width of the equipment, and height is 6.5 ft.',ref:'NEC 110.26(A)(1)',difficulty:'Apprentice',category:'Working Space'},
  {id:'q18',question:'Overload protection for a continuous-duty motor with a 1.15 service factor is sized at what % of nameplate FLA?',choices:['115%','125%','140%','250%'],correct:1,explanation:'NEC 430.32(A)(1): motors with SF ≥1.15 or a 40°C temperature rise use 125% of nameplate full-load current for overload protection.',ref:'NEC 430.32(A)(1)',difficulty:'Journeyman',category:'Motors'},
  {id:'q19',question:'NM cable ampacity must be based on which temperature column?',choices:['60°C','75°C','90°C','Whatever the conductor is rated'],correct:0,explanation:'NEC 334.80: NM cable ampacity is the 60°C column of Table 310.16, even though the conductors are 90°C rated. The 90°C rating may still be used for derating.',ref:'NEC 334.80',difficulty:'Journeyman',category:'Ampacity'},
  {id:'q20',question:'Cables run through a stud must be at least how far from the nearest edge, or be protected by a steel plate?',choices:['3/4 in','1 in','1-1/4 in','1-1/2 in'],correct:2,explanation:'NEC 300.4(A)(1): 1-1/4 in from the nearest edge of the framing member; otherwise a 1/16 in steel plate or sleeve is required.',ref:'NEC 300.4(A)(1)',difficulty:'Apprentice',category:'Wiring Methods'},
  {id:'q21',question:'Minimum burial depth for direct-buried UF cable (under 600V, no cover):',choices:['12 in','18 in','24 in','36 in'],correct:2,explanation:'NEC Table 300.5: direct burial cable = 24 in. RMC/IMC = 6 in, PVC = 18 in. Depths change under driveways and buildings.',ref:'NEC Table 300.5',difficulty:'Journeyman',category:'Underground'},
  {id:'q22',question:'EMT must be securely fastened within what distance of each box or fitting?',choices:['18 in','3 ft','5 ft','10 ft'],correct:1,explanation:'NEC 358.30(A): secure EMT within 3 ft of each box, cabinet, or termination, and at least every 10 ft thereafter.',ref:'NEC 358.30(A)',difficulty:'Apprentice',category:'Conduit'},
  {id:'q23',question:'Which receptacles in a dwelling must be tamper-resistant?',choices:['Only bedrooms','Only kitchens','All 15A/20A 125V receptacles in specified areas','None'],correct:2,explanation:'NEC 406.12: 15A and 20A, 125V and 250V receptacles in dwelling units must be listed tamper-resistant, with limited exceptions.',ref:'NEC 406.12',difficulty:'Apprentice',category:'Receptacles'},
  {id:'q24',question:'Minimum service disconnect rating for a one-family dwelling:',choices:['60A','100A','125A','200A'],correct:1,explanation:'NEC 230.79(C): the service disconnecting means for a one-family dwelling must be rated at least 100A, 3-wire.',ref:'NEC 230.79(C)',difficulty:'Apprentice',category:'Services'},
  {id:'q25',question:'Where must the service disconnecting means be located?',choices:['Anywhere on the property','Nearest the point of service conductor entrance','In the basement only','Outdoors only'],correct:1,explanation:'NEC 230.70(A)(1): the disconnect must be at a readily accessible location, either outside or inside nearest the point of entrance of the service conductors.',ref:'NEC 230.70(A)(1)',difficulty:'Journeyman',category:'Services'},
  {id:'q26',question:'For equipment rated 100A or less, terminations are assumed rated for:',choices:['60°C','75°C','90°C','No assumption'],correct:0,explanation:'NEC 110.14(C)(1)(a): circuits rated 100A or less, or marked for #14–#1 conductors, use the 60°C column unless the equipment is listed and marked otherwise.',ref:'NEC 110.14(C)',difficulty:'Journeyman',category:'Terminations'},
  {id:'q27',question:'Which is NOT a standard OCPD ampere rating?',choices:['45A','55A','70A','90A'],correct:1,explanation:'NEC 240.6(A) standard ratings: 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100... 55A is not standard.',ref:'NEC 240.6(A)',difficulty:'Journeyman',category:'Overcurrent'},
  {id:'q28',question:'The dwelling laundry branch circuit must be rated:',choices:['15A','20A','30A','Either 15A or 20A'],correct:1,explanation:'NEC 210.11(C)(2): at least one 20A branch circuit for laundry receptacles, and it may serve no other outlets.',ref:'NEC 210.11(C)(2)',difficulty:'Apprentice',category:'Branch Circuits'},
  {id:'q29',question:'Flexible cord may be used as a substitute for fixed wiring:',choices:['Always','Never','Only in commercial spaces','Only above ceilings'],correct:1,explanation:'NEC 400.12: flexible cords must not be used as a substitute for the fixed wiring of a structure, run through walls/ceilings, or concealed.',ref:'NEC 400.12',difficulty:'Apprentice',category:'Wiring Methods'},
  {id:'q30',question:'Every panelboard circuit directory must be:',choices:['Optional if the panel is labeled','Legible and specific as to each circuit purpose','Handwritten only','Located inside the enclosure only'],correct:1,explanation:'NEC 408.4(A): each circuit must be legibly identified as to its clear, evident and specific purpose. "Spare" is only allowed for a truly unused breaker.',ref:'NEC 408.4(A)',difficulty:'Apprentice',category:'Panelboards'},
];

// Whole-day number in the device's local time zone. Stable for a given calendar
// date no matter what hour it is asked, so the Home card and the scheduled
// notification always resolve to the same question.
export const dayNumber = (date = new Date()) =>
  Math.floor(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86400000);

export const getQuestionForDate = (date = new Date()) => {
  const idx = ((dayNumber(date) % NEC_QUESTIONS.length) + NEC_QUESTIONS.length) % NEC_QUESTIONS.length;
  return NEC_QUESTIONS[idx];
};

export const getDailyQuestion = () => getQuestionForDate(new Date());
